package com.cloudwise.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.time.LocalDateTime;

/**
 * CloudResource entity class.
 *
 * <p>This class maps to the "cloud_resource" table in the H2 database.
 * Each instance represents one simulated cloud resource (such as an EC2
 * instance, S3 bucket, RDS database, etc.) along with its monthly cost
 * and an automatically generated cost recommendation.</p>
 */
@Entity
@Table(name = "cloud_resource")
public class CloudResource {

    /** Unique identifier automatically generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Human-friendly name of the resource, e.g. "EC2 Web Server". */
    @Column(name = "resource_name", nullable = false)
    private String resourceName;

    /** Type of the resource, e.g. EC2, S3, RDS, ELB, EBS, Lambda. */
    @Column(name = "resource_type", nullable = false)
    private String resourceType;

    /** Region where the resource is deployed, e.g. Mumbai, Delhi. */
    @Column(nullable = false)
    private String region;

    /** Current status of the resource: Running or Stopped. */
    @Column(nullable = false)
    private String status;

    /** Monthly cost of the resource in INR. */
    @Column(name = "monthly_cost", nullable = false)
    private Double monthlyCost;

    /**
     * Cost recommendation automatically generated by the backend.
     * Users cannot set this value directly through the API.
     */
    @Column(nullable = false)
    private String recommendation;

    /** Timestamp of when the resource record was created. */
    @Column(name = "created_date", updatable = false)
    private LocalDateTime createdDate;

    /**
     * Default constructor required by JPA.
     */
    public CloudResource() {
    }

    /**
     * Called by JPA before persisting a new entity.
     * Sets the createdDate automatically.
     */
    @jakarta.persistence.PrePersist
    protected void onCreate() {
        this.createdDate = LocalDateTime.now();
    }

    /**
     * Automatically generates the recommendation based on monthly cost.
     * Called by the service layer before saving or updating a resource.
     *
     * Rule:
     *   - If monthlyCost > 5000  -> "High Cost Resource"
     *   - Otherwise              -> "Normal Resource"
     */
    public void generateRecommendation() {
        if (this.monthlyCost != null && this.monthlyCost > 5000) {
            this.recommendation = "High Cost Resource";
        } else {
            this.recommendation = "Normal Resource";
        }
    }

    // -----------------------------------------------------------------
    // Getters and Setters
    // -----------------------------------------------------------------

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getResourceName() {
        return resourceName;
    }

    public void setResourceName(String resourceName) {
        this.resourceName = resourceName;
    }

    public String getResourceType() {
        return resourceType;
    }

    public void setResourceType(String resourceType) {
        this.resourceType = resourceType;
    }

    public String getRegion() {
        return region;
    }

    public void setRegion(String region) {
        this.region = region;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Double getMonthlyCost() {
        return monthlyCost;
    }

    public void setMonthlyCost(Double monthlyCost) {
        this.monthlyCost = monthlyCost;
    }

    public String getRecommendation() {
        return recommendation;
    }

    public void setRecommendation(String recommendation) {
        this.recommendation = recommendation;
    }

    public LocalDateTime getCreatedDate() {
        return createdDate;
    }

    public void setCreatedDate(LocalDateTime createdDate) {
        this.createdDate = createdDate;
    }
}
